// examples/svelte/src/App.svelte
<script>
import { lg } from 'windijs';

  import svelteLogo from './assets/svelte.svg'
  import Counter from './lib/Counter.svelte'
  import { bg, w } from "./windi"

  const logo = [bg.orange[300], lg(bg.green[400])];
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" use:w={[bg.indigo[300]]} alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank">
      <img src={svelteLogo} class="logo svelte" use:w={logo} alt="Svelte Logo" />
    </a>
  </div>
  <!-- TODO: can svelte support Array as class param, without toString()? -->
  <!-- TODO: svelte args with array, the last element suggestion is wrong -->
  <h1 class={[bg.blue[300], bg.red[500]].toString()}>Vite + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>

// examples/preact-ts/src/app.tsx
import './app.css'

import type { WindiColors } from 'windijs'
import { bg } from './windi'
import preactLogo from './assets/preact.svg'
import { useState } from 'preact/hooks'

export function App() {
  const [count, setCount] = useState(0)
  const [button, setButtonStyle] = useState([bg.pink[400]])
  const colors: WindiColors[] = ["red", "orange", "yellow", "green", "teal", "blue", "purple", "pink"]

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" class="logo" alt="Vite logo" />
        </a>
        <a href="https://preactjs.com" target="_blank">
          {/* TODO: same problem with react, can we make class support Array? */}
          <img src={preactLogo} class={["logo", "preact", bg.blue[400].opacity(20)]} alt="Preact logo" />
        </a>
      </div>
      <h1>Vite + Preact</h1>
      <div class="card">
        <button class={button} onClick={() => {
          setButtonStyle([bg[colors[count % 8]][400]])
          setCount((count) => count + 1)
        }}>
          count is {count}
        </button>
        <p>
          Edit <code>src/app.tsx</code> and save to test HMR
        </p>
      </div>
      <p class="read-the-docs">
        Click on the Vite and Preact logos to learn more
      </p>
    </>
  )
}
